Repository cibernox/ember-power-select, pull requests merged in 2022-08, with the labels that each got.

#1529 Allow a wider range of ember-basic-dropdown versions
  .github/workflows/ci.yml
  config/ember-try.js
  node-tests/blueprints/ember-power-select.js
  package-lock.json
  package.json
Labels: enhancement

#1530 embroider-optimized support
  .github/workflows/ci.yml
  .prettierrc.js
  tests/integration/components/power-select/customization-with-components-test.js
Labels: enhancement

#1532 Fix embroider-optimized
  README.md
  config/ember-try.js
  ember-cli-build.js
  package-lock.json
  package.json
  tests/dummy/app/components/custom-group-component.js
  tests/dummy/app/components/list-of-countries.js
  tests/dummy/app/templates/components/custom-after-options-two.hbs
  tests/dummy/app/templates/components/custom-after-options.hbs
  tests/dummy/app/templates/components/custom-before-options-two.hbs
  tests/dummy/app/templates/components/custom-before-options.hbs
  tests/dummy/app/templates/components/custom-group-component.hbs
  tests/dummy/app/templates/components/custom-no-matches-message.hbs
  tests/dummy/app/templates/components/custom-placeholder.hbs
  tests/dummy/app/templates/components/custom-search-message.hbs
  tests/dummy/app/templates/components/custom-trigger-component.hbs
  tests/dummy/app/templates/components/custom-trigger-that-handles-focus.hbs
  tests/dummy/app/templates/components/list-of-countries.hbs
  tests/dummy/app/templates/components/selected-country.hbs
  tests/integration/components/power-select/customization-with-components-test.js
  tests/integration/components/power-select/customization-with-extending-components-test.js
Labels: internal

#1533 Require node >= 14, Ember >= 3.24
  .ember-cli
  .eslintignore
  .eslintrc.js
  .github/workflows/ci.yml
  .gitignore
  .npmignore
  .prettierignore
  .template-lintrc.js
  CONTRIBUTING.md
  README.md
  config/ember-try.js
  package-lock.json
  package.json
  tests/dummy/app/controllers/public-pages/cookbook/create-custom-options.js
  tests/dummy/app/index.html
  tests/dummy/config/ember-cli-update.json
  tests/dummy/config/environment.js
  tests/dummy/config/targets.js
  tests/helpers/index.js
  tests/index.html
  tests/integration/components/power-select/general-behaviour-test.js
  tests/integration/components/power-select/multiple-test.js
Labels: breaking

#1535 Add rwjblue release-it
  .github/workflows/ci.yml
  RELEASE.md
  package-lock.json
  package.json
Labels: internal
