Repository cibernox/ember-power-select, pull requests merged in 2024-03, with the labels that each got.

#1726 Update ember-basic-dropdown to v8.0.0-beta.8
  docs/package.json
  ember-power-select/package.json
  ember-power-select/src/components/power-select.hbs
  pnpm-lock.yaml
  test-app/package.json
Labels: dependencies

#1727 Minor Typo correction.
  docs/app/templates/public-pages/docs/custom-search-action.hbs
Labels: documentation

#1736 Update ember cli to 5 7
  docs/config/ember-cli-update.json
  docs/config/optional-features.json
  docs/package.json
  ember-power-select/package.json
  pnpm-lock.yaml
  test-app/config/ember-cli-update.json
  test-app/config/optional-features.json
  test-app/package.json
Labels: dependencies

#1737 Update ember-basic-dropdown to major release v8
  docs/package.json
  ember-power-select/blueprints/ember-power-select/index.js
  ember-power-select/package.json
  pnpm-lock.yaml
  test-app/package.json
Labels: dependencies

#1739 Fix rollup config (style.js -> styles.js)
  ember-power-select/rollup.config.mjs
Labels: bug

#1740 Mark ember-power-select-is-equal as public & add as note in migrate docs
  docs/app/templates/public-pages/docs/migrate-7-0-to-8-0.hbs
  ember-power-select/src/helpers/ember-power-select-is-equal.ts
Labels: documentation

#1742 Fix theme imports for vanilla js
  docs/app/templates/public-pages/docs/migrate-7-0-to-8-0.hbs
  ember-power-select/src/themes/bootstrap.js
  ember-power-select/src/themes/material.js
  ember-power-select/themes/bootstrap.js
  ember-power-select/themes/material.js
Labels: bug

#1744 Remove NodeJs info (not necessary for v2 addon)
  ember-power-select/README.md
Labels: internal

#1746 Type improvements
  ember-power-select/src/components/power-select.ts
Labels: enhancement

#1751 Bump ember-basic-dropdown to v8.0.4
  docs/package.json
  ember-power-select/package.json
  pnpm-lock.yaml
  test-app/package.json
Labels: dependencies
