Repository cibernox/ember-power-select, pull requests merged in 2024-01, with the labels that each got.

#1627 DOCS: Add additional option for css import
  docs/app/templates/public-pages/docs/installation.hbs
  docs/ember-cli-build.js
Labels: documentation

#1630 types: Separate Args and Signature
  ember-power-select/src/components/power-select-multiple.ts
  ember-power-select/src/components/power-select.ts
Labels: bug

#1635 DOCS: Fix typo & usings
  docs/app/templates/public-pages/cookbook/index.hbs
  docs/app/templates/public-pages/docs/the-search.hbs
  docs/app/templates/snippets/system-wide-config-1-js.js
Labels: documentation

#1639 Update `ember-assign-helper` to latest
  ember-power-select/package.json
  pnpm-lock.yaml
  test-app/package.json
Labels: breaking

#1640 DOCS: Remove `ember-href-to` package & replace usings
  docs/app/templates/public-pages.hbs
  docs/app/templates/public-pages/docs/index.hbs
  docs/app/templates/public-pages/docs/styles.hbs
  docs/app/templates/public-pages/docs/the-list.hbs
  docs/app/templates/public-pages/docs/the-search.hbs
  docs/app/templates/public-pages/docs/the-trigger.hbs
  docs/package.json
  pnpm-lock.yaml
Labels: documentation

#1641 Fix input width in PowerSelectMultiple
  ember-power-select/less/base.less
  ember-power-select/scss/base.scss
  ember-power-select/src/components/power-select-multiple/input.hbs
  ember-power-select/src/components/power-select-multiple/input.ts
  ember-power-select/src/components/power-select-multiple/trigger.hbs
Labels: bug

#1642 Update dependencies
  docs/package.json
  ember-power-select/package.json
  ember-power-select/src/components/power-select-multiple/input.hbs
  ember-power-select/src/components/power-select.hbs
  ember-power-select/src/components/power-select/before-options.hbs
  ember-power-select/src/components/power-select/trigger.hbs
  pnpm-lock.yaml
  test-app/package.json
Labels: dependencies

#1649 Set `args.options` as optional
  ember-power-select/src/components/power-select.ts
Labels: enhancement

#1651 Update eslint-plugin-ember to 12.0.0
  docs/.eslintrc.js
  docs/package.json
  ember-power-select/.eslintrc.cjs
  ember-power-select/package.json
  ember-power-select/src/components/power-select/no-matches-message.ts
  ember-power-select/src/components/power-select/placeholder.ts
  ember-power-select/src/components/power-select/power-select-group.ts
  ember-power-select/src/components/power-select/search-message.ts
  package.json
  pnpm-lock.yaml
  test-app/.eslintrc.js
  test-app/package.json
Labels: dependencies

#1652 Update ember-basic-dropdown
  docs/package.json
  ember-power-select/package.json
  pnpm-lock.yaml
  test-app/package.json
Labels: dependencies

#1660 DOCS: Fix scss import statement
  docs/app/components/snippets/installation-1.scss
Labels: documentation

#1672 Update ember cli to v5.6
  docs/config/ember-cli-update.json
  docs/package.json
  pnpm-lock.yaml
  test-app/config/ember-cli-update.json
  test-app/package.json
Labels: dependencies
