Repository cibernox/ember-power-select, pull requests merged in 2024-02, with the labels that each got.

#1682 Convert `@task` to the async-arrow fn
  ember-power-select/babel.config.json
  ember-power-select/src/components/power-select.ts
Labels: enhancement

#1684 Stricter dep management
  .npmrc
  docs/package.json
  ember-power-select/package.json
  pnpm-lock.yaml
  test-app/package.json
  test-app/tests/integration/components/power-select/general-behaviour-test.js
Labels: internal

#1685 Update ember-concurrency to v4 and move to peerDependencies
  docs/app/templates/public-pages/docs/installation.hbs
  docs/ember-cli-build.js
  docs/package.json
  ember-power-select/babel.config.json
  ember-power-select/blueprints/ember-power-select/index.js
  ember-power-select/package.json
  pnpm-lock.yaml
  test-app/ember-cli-build.js
  test-app/package.json
Labels: breaking

#1686 DOCS: Add section "Migrate from 7.0 to 8.0"
  docs/app/controllers/public-pages/docs.js
  docs/app/router.ts
  docs/app/routes/public-pages/docs/migrate-7-0-to-8-0.ts
  docs/app/templates/public-pages/docs.hbs
  docs/app/templates/public-pages/docs/custom-search-action.hbs
  docs/app/templates/public-pages/docs/installation.hbs
  docs/app/templates/public-pages/docs/migrate-7-0-to-8-0.hbs
  docs/app/templates/public-pages/docs/test-helpers.hbs
  docs/tests/unit/routes/public-pages/docs/migrate-7-0-to-8-0-test.ts
Labels: documentation

#1687 Forward @highlightOnHover & @typeAheadOptionMatcher on multiple select
  ember-power-select/src/components/power-select-multiple.hbs
Labels: bug

#1692 Update ember-basic-dropdown to 8.0.0-beta.6
  docs/package.json
  ember-power-select/package.json
  pnpm-lock.yaml
  test-app/package.json
  test-app/tests/integration/components/power-select/a11y-test.js
Labels: dependencies

#1693 Update ember-basic-dropdown to 8 beta 7
  docs/package.json
  ember-power-select/package.json
  pnpm-lock.yaml
  test-app/package.json
Labels: dependencies

#1714 fix: `Type error: (n.selected || []).slice is not a function` in multiple select
  ember-power-select/src/components/power-select-multiple.ts
Labels: bug

#1715 Fix `NoMatchesMessage` component missing splattributes
  ember-power-select/src/components/power-select/no-matches-message.hbs
Labels: bug
